### ISSUE TITLE
Замечание 

### ISSUE THREAD

**Issue by yaizida** [breemy1337/website#1]
https://github.com/breemy1337/website/blob/90c1e38ff26dca9cb3664e8a6bf24cdf347a93b8/website/posts/models.py#L32

Кавычки должны быть однородными, если используешь везде в  файле одинарные то везде и должны быть одинарными. За исключением вложенных

**Comment by yaizida** [comment]
Good work

**Comment by breemy1337** [comment]
thank my friend
